### ISSUE TITLE
Error: registro

### ISSUE THREAD

**Issue by javierreraul** [UNIZAR-30226-2020-09/FE-web#33]
![image](https://user-images.githubusercontent.com/56364932/79635475-72785e00-8171-11ea-82e8-b5dfc38e8a78.png)

El registro me ha llevado aquí después de procesar durante 5-10 segundos la petición

**Comment by Uncastellum** [comment]
@javierreraul Intenta replicar el error: es la primera vez q inicial la pág? al recargar?

**Comment by javierreraul** [comment]
No he sabido replicarlo... Y ahora tampoco. Mirad la consola de heroku porque os ha debido de dar un buen error interno

**Comment by Uncastellum** [comment]
El error es debido a un problema de red, pasa a veces.
No sabemos como controlarlo (salto de fe)
