### ISSUE TITLE
Cosa mejorable: login

### ISSUE THREAD

**Issue by javierreraul** [UNIZAR-30226-2020-09/FE-web#34]
Podríais guardaros el token en el navegador (hasta que pruebe y caduque) para que no se tenga que iniciar sesión cada vez que se recarga la web

**Comment by Uncastellum** [comment]
Token guardado actualmente como cookie, no entiendo el error o la mejora¿?
@javierreraul

**Comment by javierreraul** [comment]
Si cierras la pestaña y vuelves a abrir en la misma ventana del navegador otra pestaña con la página no recuerda dicho token... No tengo ni idea de cómo estaréis almacenando la cookie pero estaría bien que fuera persistente al menos con la sesión de esa propia ventana. @Uncastellum

**Comment by Uncastellum** [comment]
@javierreraul 
Lo tomo en cuenta, se de donde viene el error (problema de estados de react) 
Este arreglo esta pendiente para la próxima iteración (complejidad media)
Referencia: #46
