### ISSUE TITLE
Error: comprobaciones de password en el registro

### ISSUE THREAD

**Issue by javierreraul** [UNIZAR-30226-2020-09/FE-web#37]
No hacéis ningún tipo de comprobación de la password en el registro... Me he registrado poniendo de contraseña "a"

Clave maestra / Master password:
Para registrarse/iniciar sesión, está asociada para iniciar sesión:
- Número mínimo: 8 caracteres incluidos
- Número máximo: 40 caracteres incluidos
Puede tener todo tipo de caracteres, pero ha de tener:
- 1 minúscula
- 1 mayúscula
- 1 número
- 1 carácter especial @#$%!

**Comment by JesusAngelGonzalez** [comment]
La resuelvo yo

**Comment by Uncastellum** [comment]
@JesusAngelGonzalez 
Rellena la función que se encuentra en utils.js
Tambien hay que avisar al usuario de cuales son los requisitos de la contraseña -> crea un pop-up al pasar el raton/clicar en el campo que muestre esa info (https://www.w3schools.com/howto/howto_js_popup.asp)
En el error simplemente que verifique que: "formato correcto" o "incorrecto"

**Comment by Uncastellum** [comment]
Avisos de error + comprobaciones en 18cec85ff2355d73a1f834d7000ce7b6e4a50bca
A la espera de POP-UP

**Comment by Uncastellum** [comment]
POP-UP 2c8d21b87c667b6243cd3691359ecc80c81f6003
