### ISSUE TITLE
No me parece del todo bien que haya una opción de "Mis contraseñas" y no una de "Mis categorías"

### ISSUE THREAD

**Issue by javierreraul** [UNIZAR-30226-2020-09/FE-web#42]
![image](https://user-images.githubusercontent.com/56364932/79635923-401c3000-8174-11ea-827b-5fade1380aad.png)
Es algo bastante secundario, pero tener la gestión de las categorías en "Ajustes" me parece a mí algo bastante raro. También os digo que es subjetivo y que evidentemente es algo que ya pensasteis en su momento al diseñar la GUI y os debió de parecer bien (y a mí, que no dije nada). Solo pensadlo y valoradlo, si no cambiáis nada ahora, será entendible y respetable :)

**Comment by Uncastellum** [comment]
@javierreraul 
Posible cambio: Mis contraseñas -> Contraseñas
No te puedo ofrecer una pág entera solo para las contraseñas

**Comment by javierreraul** [comment]
No entiendo "No te puedo ofrecer una pág entera solo para las contraseñas"

**Comment by Uncastellum** [comment]
Esto: web.com/categorias
Ademas, nuestro diseño esta aprobado por todos y esta así en el mapa de navegación que se entregó
Si quieres que haga el cambio de "Mis contraseñas -> Contraseñas" puedes reabrir el issue @javierreraul , else se queda cerrado
