### ISSUE TITLE
Información de las contraseñas

### ISSUE THREAD

**Issue by javierreraul** [UNIZAR-30226-2020-09/FE-web#43]
![image](https://user-images.githubusercontent.com/56364932/79635981-c9336700-8174-11ea-94d1-23c4998fd25f.png)
Esto creo que es menos subjetivo... Me parece bastante feo cómo presentáis la información de las contraseñas (la apariencia y la forma de hacerlo: "TextoOpcional"). De todas formas falta información que considero importante, como la categoría, los días de expiración...

**Comment by Uncastellum** [comment]
El mostrar contraseñas completo lo dejamos pendiente para la siguiente iteración debido a que nos hemos adelantado con otros aspectos (Categorias y 2FA)

**Comment by Uncastellum** [comment]
Marcaremos ahora este issue para controlar el estado de esta funcionalidad
closes #30

**Comment by Uncastellum** [comment]
Funcionalidad en 9a8bfdf2dde1494e4cf4972db80aff9733089038
BUGS APARENTES:
 - [ ] Mobile -> problemas en la columna de dos elementos (expira-cat)
Mejoras:
 - [ ] Cambiar colores y tipografia (tamaño letra)
 - [ ] Ocultar contraseña a primera vista + boton
