### ISSUE TITLE
Bugs visuales web con pantalla completa.

### ISSUE THREAD

**Issue by Aleparicio** [UNIZAR-30226-2020-09/FE-web#52]
Se han detectado los siguientes bugs visualtes, imágenes adjuntas.
<img width="709" alt="BugVisual1" src="https://user-images.githubusercontent.com/57791380/79775886-2f66e800-8335-11ea-86db-1101c98c604e.PNG">
<img width="764" alt="BugVisual2" src="https://user-images.githubusercontent.com/57791380/79775892-30981500-8335-11ea-82be-de452fea2171.PNG">

**Comment by Uncastellum** [comment]
En proceso: Limitado correo a 100 char
