### ISSUE TITLE
Error campos formularios.

### ISSUE THREAD

**Issue by Aleparicio** [UNIZAR-30226-2020-09/FE-web#53]
No está limitado el número de carácteres de muchos formularios, se ha acordado con android que los limitáis en front-end, el límite actual de backend es 255, se podría modificar si es necesario.

Formulario de contacto:
<img width="687" alt="Texto2" src="https://user-images.githubusercontent.com/57791380/79776336-e2374600-8335-11ea-8ac8-f91037e81964.PNG">
<img width="598" alt="Texto" src="https://user-images.githubusercontent.com/57791380/79776338-e2cfdc80-8335-11ea-9e82-def85c08a2dd.PNG">

Al crea categorías lo mismo.

**Comment by sergioge99** [comment]
Arreglado :)

**Comment by Uncastellum** [comment]
Expandelo a registro (modifica utils) y quita los ifs (lenght > ....)

**Comment by sergioge99** [comment]
done
