### ISSUE TITLE
BUGS VISUALES // Mejoras

### ISSUE THREAD

**Issue by Uncastellum** [UNIZAR-30226-2020-09/FE-web#61]
Si encontrais algún bug visual **Y NO CRASH**, mandadlo por este hilo

**BUGS**
 - [x] ~~Los bordes de mostrar contraseña se cortan~~
 - [x] ~~Las columnas de Expiración y Categorias salen raras en MOBILE~~
 - [x] ~~Texto opcional no muestra saltos de linea~~
 - [x] ~~El acordeón inferior de Mis Contraseñas no tiene margen~~
 - [x] ~~No existe -> No existe/n (Alerta al crear/modificar grupales)~~
 - [x] ~~Limitar el campo longitud~~
 - [x] ~~Mostrar contraseñas: Categoria invade espacio de Expira en~~
 - [x] ~~En compartir contraseñas aparece un padding extraño en el simbolo +~~
 - [x] ~~Bienvenido a pandora se sale de la pantalla~~
 - [x] ~~dias -> días (en mostrar contraseñas)~~
 - [x] ~~Eliminar ":" en los campos de edición de texto tanto en la pantalla de inicio de sesión como en la principal (cuando ya has iniciado sesión) en los formularios de contacto~~
 - [x] ~~Enter para confirmar a la hora de compartir~~

**MEJORAS**
 - [x] ~~Cambiar colores y tipografía + tamaño letra (Información de las contras)~~
 - [x] ~~Ocultar contraseña a primera vista + boton (Información de las contras)~~
 - [x] ~~Contraseñas Expiradas: poner alguna admiración o algo junto al título de la contra a parte del cambio de color~~
 - [x] ~~http -> https~~

**WON'T FIX**
 - [x] fas fa-times ( x ) en creación de contraseñas o modificación para salir
 - [x] En compartir contraseña, poniendo el último usuario añadido, solo se envía dandole al +. Es poco intuitivo. Sería conveniente un botón de confirmar, o que al crear la contrseña se leyese es último campo también.
 - [x] En el ordenador, al volver hacia detrás cuando estamos creando una constraseña, redirige a "Incio". Mejor redirigir a la lista de todas las contraseñas.
 - [x] Al eliminar una contraseña y categoría, añadir una ventana emergente donde pregunta: ¿Está seguro de borrar la categoría/contraseña X? 
 - [x] Cambiar "Comprometidas" por "Datos comprometidos", añadir aviso de que se trata de un servicio externo y que este se abra en otra pestaña
 - [x] ~~En el Bienvenido a pandora un \<br\> obligatorio~~

.

**Comment by javierreraul** [comment]
/cc @Uncastellum @JesusAngelGonzalez @sergioge99 
"Cambiar "Comprometidas" por "Datos comprometidos", añadir aviso de que se trata de un servicio externo y que este se abra en otra pestaña", intentad tenerlo antes de que el resto se ponga a testear, porfa.

**Comment by Uncastellum** [comment]
He estado leyendo y no creo q sea posible sin modificar gran parte del código, por el momento se deja en WONT FIX
