### ISSUE TITLE
Creación de contraseña compartida se carga la cuenta

### ISSUE THREAD

**Issue by javierreraul** [UNIZAR-30226-2020-09/FE-web#67]
1. ¿Cómo se crea una contraseña compartida si no?
2. Si no se puede porque va a hacer que crashee, no dejéis la opción

![image](https://user-images.githubusercontent.com/56364932/82031307-f7d02f00-9699-11ea-8e2b-7df673e5a7e1.png)

**Comment by javierreraul** [comment]
![image](https://user-images.githubusercontent.com/56364932/82031891-c86df200-969a-11ea-988e-d124b7917ccb.png)
Además se pone como por defecto xD

**Comment by Uncastellum** [comment]
c56e46492bfa974bb503dfe9b6c68226fd38812c
