### ISSUE TITLE
FALLO AL LISTAR

### ISSUE THREAD

**Issue by javierreraul** [UNIZAR-30226-2020-09/FE-web#70]
BACKEND, ECHADLE UN OJO:
1. Creación de dos contraseñas con categoría "Redes Sociales"
2. Eliminación de todas las categorías excepto "Sin categoría" y "Compartida"
3. No funciona el listar

![image](https://user-images.githubusercontent.com/56364932/82032069-05d27f80-969b-11ea-9c94-5dc1565d7e08.png)
![image](https://user-images.githubusercontent.com/56364932/82032239-3b776880-969b-11ea-85cd-e663a8d210bb.png)

**Comment by Uncastellum** [comment]
c56e46492bfa974bb503dfe9b6c68226fd38812c
