### ISSUE TITLE
Redirección + cerrar sesión en otra pestaña problema

### ISSUE THREAD

**Issue by Aleparicio** [UNIZAR-30226-2020-09/FE-web#74]
Tenía dos pestañas de pandora abiertas con la sesión iniciada en, al menos, la que estaba visualizando. He cerrado sesión y mozilla me ha abierto la otra pestaña, saliendo el error de no se han podido listar contraseñas. Al parecer estaba en la pestaña de help, pero en lugar de hacerse la redirección me había quedado atrapado en una pestaña de pandora sin información ni forma de ir a otra pestaña. Cambiando la url he ido a home y me ha salto error de error al listar contraseñas grupales y error al listar contraseñas. AL volver a recargar ya no ha aparecido el error. No he podido volver a iniciar contraseña por no disponer ahora mismo del 2fa.

**Comment by Uncastellum** [comment]
Es necesario hacer rediseño en redireccion de botones externos a nuestra web, algo como 
https://stackoverflow.com/questions/45046030/maintaining-href-open-in-new-tab-with-an-onclick-handler-in-react
