### ISSUE TITLE
Limitar el campo longitud

### ISSUE THREAD

**Issue by raulrhs** [UNIZAR-30226-2020-09/FE-web#76]
Al pulsar generar contraseña, nos mandais el numero que sea a backend y si es muy grande hace overflow y da error. Limitad el campo para que os quepa en un entero tanto a vosotros como a nosotros.
![image](https://user-images.githubusercontent.com/41389217/82155690-13446100-9877-11ea-8c45-d7f6dcc8d2cb.png)

**Comment by JesusAngelGonzalez** [comment]
Lo he limitado para que siempre sea un minimo de 4 y un maximo de 40, que si no me equivoco es lo que se hablo en su momento
