### ISSUE TITLE
Hitbox de los mensajes de información

### ISSUE THREAD

**Issue by raulrhs** [UNIZAR-30226-2020-09/FE-web#78]
Los mensajes de información (en este caso el de edicion de la categoria "aasdasd", pero pasa con cualquiera) tienen una "hitbox" que ocupa todo el ancho de pantalla, por tanto mientras estan presentes no puedes clicar nada a su izquierda o derecha (ni debajo obviamente), en este caso no puedo clicar el boton inicio (solo puedo por la parte de abajo). He probado con 6+ mensajes de informacion u no puedes clicar nada a los lados.
![image](https://user-images.githubusercontent.com/41389217/82156226-4a684180-987a-11ea-96dd-0ad840924c51.png)

**Comment by Uncastellum** [comment]
Arreglado en a83bf14f2c92c0ad80411ab231b16a75b0005e47
