### ISSUE TITLE
IMPORTANTE: Error al editar una contraseña normal y pasarla a compartida

### ISSUE THREAD

**Issue by javierreraul** [UNIZAR-30226-2020-09/FE-web#79]
Al editar una contraseña NO GRUPAL, si le das a la opción "Compartir", seleccionas los usuarios con los que vas a compartir y le das a guardar, parece que la petición que se manda es la de editar una contraseña NO grupal, puesto que:
1. Si se comparte con alguien que no existe, no sale la retroalimentación de "la contraseña no ha podido ser compartida con X usuario".
2. Si se comparte con alguien que existe, al guardar los cambios, la contraseña no pasa a ser compartida.
Ahora no tengo acceso al Heroku CLI, pero revisad qué petición estáis mandando.

**Comment by JesusAngelGonzalez** [comment]
El punto 1 ya esta arreglado, pero el punto 2 ni Sergio ni yo hemos sido capaces de replicarlo, y a ambos nos funciona bien el paso de contraseña individual a compartida y viceversa.
